---
name: push-bundles

on:
  push:
    branches:
    - main
    paths:
    - policy

  workflow_dispatch:

jobs:
  push-policy-bundles:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      uses: docker/login-action@v2
      with:
        # See also BUNDLE_REPO defined in Makefile
        registry: quay.io
        username: ${{ secrets.BUNDLE_PUSH_USER }}
        password: ${{ secrets.BUNDLE_PUSH_PASS }}

    - name: Install conftest
      run: make install-conftest CONFTEST_BIN=$HOME/.local/bin

    - name: Push bundles
      run: make push-bump
